default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: url_shortener
  password: url_shortener

development:
  <<: *default
  database: url_shortener_development
  host: localhost

test:
  <<: *default
  database: url_shortener_test

production:
  <<: *default
  database: url_shortener_production
  username: url_shortener
  password: <%= ENV['URL_SHORTENER_DATABASE_PASSWORD'] %>
